<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Single Back arrow</name>
   <tag></tag>
   <elementGuidId>ceda47d0-809b-43e4-920b-883694780665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app-container&quot;]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-container&quot;]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-container&quot;]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
